name: CI - Automação API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Altere se seu projeto usar outra versão

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test  # Altere se o comando de testes for diferente